version: "3.9"
services:
  support_bot:
    build: .
    ports:
      - 8000:8000

  nginx:
   container_name: nginx
   image: nginx:1.15-alpine
   depends_on:
     - support_bot
   restart: always
   build: ./nginx
   ports:
     - "8080:8080"
   volumes:
      - ./data/nginx:/etc/nginx/conf.d
   

