version: "3.9"
services:
  support_bot_fastapi:
    build: .
    ports:
      - 8000:8000

  nginx:
   container_name: nginx_fastapi
   image: nginx
   restart: always
   build: ./nginx
   ports:
     - "8080:8080"
   depends_on:
     - support_bot_fastapi