version: "3.9"
services:
  support_bot:
    build: .
    ports:
      - 8010:8010

  nginx:
   container_name: nginx
   image: nginx
   restart: always
   build:
     context: ./nginx
     dockerfile: nginx_Dockerfile
   ports:
     - "8080:8080"
   depends_on:
     - support_bot